### ISSUE TITLE
R package?

### ISSUE THREAD

**Issue by iferres** [ghoresh11/twilight#3]
Hi Dr Horesh, very interesting paper! Congratulations

Just a question, are you planning implement the methods into an R package? I think it would be very valuable for the pangenomics community and actually you are half the way with this repository already. 

I'm a PhD student from Gregorio Iraola's Lab in Montevideo. My colleagues told me you were here in 2019, but I was in France at that moment in an internship at Institut Pasteur (working with Amine Ghozlane, I think you met him here also).

We have [recently published Pagoo](https://www.cell.com/cell-reports-methods/fulltext/S2667-2375(21)00140-5) a tool for pangenomics analysis in R, and it would be great to have a recipe to apply some of the twilight methods you developed. 

On the [webpage](https://iferres.github.io/pagoo) there's a tab with what we called "Recipes" with applications of pagoo in concert with other R packages. In particular, [there's one](https://iferres.github.io/pagoo/articles/Recipes.html#population-structure) with some steps to create a phylogeny, infer lineages with Rhierbaps, and then to add this information to the pangenome object. I'm thinking on a function that could take a pan-matrix and lineage information, and classify each cluster of genes into a "Horesh category" (😎), or something like that.

What do you think?

Regards,
Ignacio

**Comment by ghoresh11** [comment]
Hi Ignacio,

I'm really happy you like the paper and that you find it valuable. Too bad I missed you in Montevideo, say hello to Gregorio from me :)

The script as it is essentially does what you suggest. I can imagine that it would be a nice feature to integrate it in Pagoo. Is there a way to integrate it in Pagoo in its current form? I'm now working in industry so I don't have immediate bandwidth to work on this, but I will keep in mind, especially if more people are interested.

Best
Gal

**Comment by iferres** [comment]
Thank you for your answer, Gal.  

Pagoo runs interactively in the R session, so is better to have the output already there, but you can always grab it from a file so there's no problem with that. When I find some time I will try to distil your script and make a function with that so I can write a cleaner recipe, tho. I will write you back if I achieve something to let you know, if you mind. 

Bests!!
Ignacio
